#!/usr/bin/env python3
"""
generate_appendix_tables_a03.py — Generate paper-ready LaTeX appendix tables from Gate A03 results.
Reads directly from evaluation/benchmark/v2/paper_ready_a03/ and updates manuscript tables.
"""

from pathlib import Path
import re
import numpy as np
import pandas as pd

REPO_ROOT = Path(__file__).resolve().parents[2]
PAPER_READY = REPO_ROOT / "evaluation/benchmark/v2/paper_ready_a03"

PREPRINTS_OUT = REPO_ROOT / "docs/papers/_42_01_Benchmark_PrePrints/generated/appendix_performance_tables.tex"
BENCHMARK_OUT = REPO_ROOT / "docs/papers/_42_Benchmark/generated/appendix_performance_tables.tex"

ALL_14 = [
    "Elliptic", "DGraphFin", "BitcoinOTC", "Ethereum", "BSC", "Polygon",
    "Yelp-Syn", "Amazon-Syn", "Reddit-Syn", "Flickr-Syn", "Cora-Syn", "CiteSeer-Syn", "PubMed-Syn",
    "LANL-RedTeam"
]

MODELS_8 = [
    "DOMINANT", "AnomalyDAE", "CoLA", "CONAD-corrected",
    "GADNR", "OCGNN", "DLG-Base", "DLG-Aug"
]

MODEL_DISPLAY = {
    "DOMINANT": "DOMINANT",
    "AnomalyDAE": "AnomalyDAE",
    "CoLA": "CoLA",
    "CONAD-corrected": "CONAD",
    "GADNR": "GADNR",
    "OCGNN": "OCGNN",
    "DLG-Base": "DLG-Base",
    "DLG-Aug": "DLG-Aug"
}


def parse_cell(val_str):
    if not isinstance(val_str, str) or val_str in ["OOM", "FAIL", "N/A", "---"]:
        return None, None
    m = re.match(r"([0-9\.]+)\s*±\s*([0-9\.]+)", val_str.strip())
    if m:
        return float(m.group(1)), float(m.group(2))
    try:
        return float(val_str), 0.0
    except ValueError:
        return None, None


def generate_table():
    df_pr = pd.read_csv(PAPER_READY / "table_main_13_pr_auc.csv", keep_default_na=False).set_index("dataset")
    df_roc = pd.read_csv(PAPER_READY / "table_main_13_roc_auc.csv", keep_default_na=False).set_index("dataset")
    df_f1 = pd.read_csv(PAPER_READY / "table_main_13_f1.csv", keep_default_na=False).set_index("dataset")

    lines = []
    lines.append("% Auto-generated appendix performance table from frozen Gate A03 benchmark artifacts")
    lines.append("% Generated by scripts/manuscript/generate_appendix_tables_a03.py")
    lines.append("\\begin{table*}[p]")
    lines.append("\\centering")
    lines.append("\\caption{Comprehensive Five-Seed Performance Profile Across All 13 Primary and External Benchmark Datasets (Gate A03 Corrective Release). Values report mean $\\pm$ standard deviation across five model seeds. Bold indicates best supported performance, italics indicate second-best; dashes (---) denote unsupported configurations under the fail-closed exact protocol.}")
    lines.append("\\label{tab:appendix_all_detailed}")
    lines.append("\\scriptsize")
    lines.append("\\setlength{\\tabcolsep}{3.2pt}")
    lines.append("\\renewcommand{\\arraystretch}{0.92}")
    lines.append("\\resizebox{\\textwidth}{!}{%")
    lines.append("\\begin{tabular}{llcccccccc}")
    lines.append("\\toprule")
    lines.append("\\textbf{Dataset} & \\textbf{Metric} & " + " & ".join(f"\\textbf{{{MODEL_DISPLAY[m]}}}" for m in MODELS_8) + " \\\\")
    lines.append("\\midrule")

    for i, d_name in enumerate(ALL_14):
        if d_name not in df_pr.index:
            continue
        
        display_d = d_name.replace("-Syn", "")
        
        metrics_data = [
            ("ROC-AUC", df_roc.loc[d_name]),
            ("PR-AUC", df_pr.loc[d_name]),
            ("F1-Score", df_f1.loc[d_name])
        ]

        for m_idx, (m_label, row_series) in enumerate(metrics_data):
            cell_vals = {}
            numeric_vals = []
            for m in MODELS_8:
                mean_v, std_v = parse_cell(row_series.get(m, "---"))
                cell_vals[m] = (mean_v, std_v)
                if mean_v is not None:
                    numeric_vals.append((m, mean_v))
            
            # Rank to find best and second best
            numeric_vals.sort(key=lambda x: x[1], reverse=True)
            best_m = numeric_vals[0][0] if len(numeric_vals) > 0 else None
            second_m = numeric_vals[1][0] if len(numeric_vals) > 1 else None

            row_tokens = []
            for m in MODELS_8:
                mean_v, std_v = cell_vals[m]
                if mean_v is None:
                    row_tokens.append("---")
                else:
                    s = f"{mean_v:.4f} $\\pm$ {std_v:.4f}"
                    if m == best_m:
                        row_tokens.append(f"\\textbf{{{s}}}")
                    elif m == second_m:
                        row_tokens.append(f"\\textit{{{s}}}")
                    else:
                        row_tokens.append(s)

            d_col = f"\\multirow{{3}}{{*}}{{{display_d}}}" if m_idx == 0 else ""
            lines.append(f"{d_col} & {m_label} & " + " & ".join(row_tokens) + " \\\\")

        if i < len(ALL_14) - 1:
            lines.append("\\midrule")

    lines.append("\\bottomrule")
    lines.append("\\end{tabular}%")
    lines.append("}")
    lines.append("\\begin{tablenotes}[flushleft]")
    lines.append("\\scriptsize")
    lines.append("\\item \\textit{Notes:} Datasets with the \\texttt{-Syn} suffix represent standardized synthetic attribute/structural anomaly injections (seed 42), whereas \\texttt{Elliptic}, \\texttt{DGraphFin}, \\texttt{BitcoinOTC}, \\texttt{Ethereum}, \\texttt{BSC}, and \\texttt{Polygon} are real-world transaction graphs. \\texttt{LANL-RedTeam} is an external real enterprise authentication graph. GADNR on Ethereum, BSC, Polygon, Elliptic, DGraphFin, Yelp-Syn, Flickr-Syn, Reddit-Syn; AnomalyDAE on Ethereum, Elliptic, DGraphFin, Yelp-Syn, Reddit-Syn, Amazon-Syn, Flickr-Syn, PubMed-Syn; and CONAD on Reddit-Syn were unsupported under the exact fail-closed operational budget and omitted without score fabrication.")
    lines.append("\\end{tablenotes}")
    lines.append("\\end{table*}")
    lines.append("")

    tex_content = "\n".join(lines)

    for p in [PREPRINTS_OUT, BENCHMARK_OUT]:
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(tex_content, encoding="utf-8")
        print(f"Saved LaTeX appendix table to {p}")


if __name__ == "__main__":
    generate_table()
