"""
Generate paper-ready LaTeX appendix performance tables from frozen Round 5 and LANL artifacts.
Guarantees 100% numerical consistency with seed_aggregated_performance.csv and support matrix.
"""

import math
from pathlib import Path
import pandas as pd

REPO_ROOT = Path(__file__).resolve().parents[3]

ROUND5_SUMMARY = REPO_ROOT / "dlg_gnn/outputs/benchmark/sci_round5_final/summary/seed_aggregated_performance.csv"
SUPPORT_MATRIX = REPO_ROOT / "dlg_gnn/outputs/benchmark/sci_round5_final/manifests/model_dataset_support_matrix_v2.csv"
LANL_SUMMARY = REPO_ROOT / "dlg_gnn/outputs/benchmark/sci_defense_extension_real_final/tables/table_d2_lanl_external_validation.csv"

OUT_GENERATED = REPO_ROOT / "dlg_gnn/docs/papers/_42_Benchmark/generated/appendix_performance_tables.tex"
OUT_APPENDIX = REPO_ROOT / "dlg_gnn/docs/papers/_42_Benchmark/appendix_financial_results.tex"

DATASET_ORDER = [
    ("Elliptic", "Elliptic", "Real Financial Fraud"),
    ("DGraphFin", "DGraphFin", "Real Financial Fraud"),
    ("BitcoinOTC", "BitcoinOTC", "Real Trust / Fraud"),
    ("Yelp", "Yelp-Syn", "Synthetic Review Fraud"),
    ("Amazon", "Amazon-Syn", "Synthetic E-Commerce Fraud"),
    ("Reddit", "Reddit-Syn", "Synthetic Social Anomaly"),
    ("Flickr", "Flickr-Syn", "Synthetic Social Anomaly"),
    ("Cora", "Cora-Syn", "Synthetic Citation Anomaly"),
    ("CiteSeer", "CiteSeer-Syn", "Synthetic Citation Anomaly"),
    ("PubMed", "PubMed-Syn", "Synthetic Citation Anomaly"),
]

MODELS = ["DOMINANT", "AnomalyDAE", "CoLA", "CONAD", "GADNR", "OCGNN", "DLG-Base", "DLG-Aug"]
METRICS = [
    ("ROC-AUC", "roc_auc_mean", "roc_auc_std"),
    ("PR-AUC", "pr_auc_mean", "pr_auc_std"),
    ("F1-Score", "validation_f1_mean", "validation_f1_std"),
]


def format_cell(mean_val, std_val=None, is_best=False, is_second=False, show_std=False):
    if mean_val is None or math.isnan(mean_val):
        return "---"
    if show_std and std_val is not None and not math.isnan(std_val):
        val_str = f"{mean_val:.4f} $\\pm$ {std_val:.4f}"
    else:
        val_str = f"{mean_val:.4f}"
    
    if is_best:
        return f"\\textbf{{{val_str}}}"
    elif is_second:
        return f"\\textit{{{val_str}}}"
    return val_str


def generate_latex():
    df_perf = pd.read_csv(ROUND5_SUMMARY)
    df_sup = pd.read_csv(SUPPORT_MATRIX)
    
    # Map (dataset, model) -> support_status
    support_map = {}
    for _, row in df_sup.iterrows():
        support_map[(row["dataset"], row["model"])] = (row["supported"], row["support_status"])

    # Map (dataset, model) -> perf_dict
    perf_map = {}
    for _, row in df_perf.iterrows():
        perf_map[(row["dataset"], row["model"])] = row

    lines = []
    lines.append("% Auto-generated appendix performance table from frozen Round 5 benchmark artifacts")
    lines.append("% Generated by scripts/manuscript/generate_appendix_tables.py")
    lines.append("\\begin{table*}[p]")
    lines.append("\\centering")
    lines.append("\\caption{Comprehensive Five-Seed Performance Profile Across All Ten Primary Benchmark Datasets (Appendix). Values report mean $\\pm$ standard deviation across five model seeds. Bold indicates best supported performance, italics indicate second-best; dashes (---) denote unsupported configurations under the fail-closed exact protocol.}")
    lines.append("\\label{tab:appendix_all_detailed}")
    lines.append("\\scriptsize")
    lines.append("\\begin{tabularx}{\\textwidth}{llXXXXXXXX}")
    lines.append("\\toprule")
    lines.append("\\textbf{Dataset} & \\textbf{Metric} & \\textbf{DOMINANT} & \\textbf{AnomalyDAE} & \\textbf{CoLA} & \\textbf{CONAD} & \\textbf{GADNR} & \\textbf{OCGNN} & \\textbf{DLG-Base} & \\textbf{DLG-Aug} \\\\")
    lines.append("\\midrule")

    for raw_ds, disp_name, domain_note in DATASET_ORDER:
        first_metric = True
        for met_label, mean_col, std_col in METRICS:
            row_vals = []
            valid_means = []
            for m in MODELS:
                sup, stat = support_map.get((raw_ds, m), (False, "unsupported"))
                if sup and (raw_ds, m) in perf_map:
                    val = perf_map[(raw_ds, m)][mean_col]
                    row_vals.append((val, perf_map[(raw_ds, m)][std_col]))
                    valid_means.append(val)
                else:
                    row_vals.append((None, None))

            sorted_unique = sorted(list(set(valid_means)), reverse=True)
            best_val = sorted_unique[0] if len(sorted_unique) > 0 else None
            second_val = sorted_unique[1] if len(sorted_unique) > 1 else None

            cells = []
            for mean_v, std_v in row_vals:
                is_best = (mean_v == best_val) if (mean_v is not None and best_val is not None) else False
                is_second = (mean_v == second_val) if (mean_v is not None and second_val is not None) else False
                cells.append(format_cell(mean_v, std_v, is_best, is_second, show_std=True))

            ds_cell = f"\\multirow{{3}}{{*}}{{{disp_name}}}" if first_metric else ""
            lines.append(f"{ds_cell} & {met_label} & " + " & ".join(cells) + " \\\\")
            first_metric = False
        lines.append("\\midrule")

    # Remove the last \midrule and replace with \bottomrule
    if lines[-1] == "\\midrule":
        lines[-1] = "\\bottomrule"
    else:
        lines.append("\\bottomrule")

    lines.append("\\end{tabularx}")
    lines.append("\\begin{tablenotes}[flushleft]")
    lines.append("\\scriptsize")
    lines.append("\\item \\textit{Notes:} Datasets with the \\texttt{-Syn} suffix represent standardized synthetic attribute/structural anomaly injections (seed 42), whereas \\texttt{Elliptic}, \\texttt{DGraphFin}, and \\texttt{BitcoinOTC} are real-world transaction graphs. GADNR on Elliptic, DGraphFin, Yelp-Syn, Flickr-Syn, Reddit-Syn, AnomalyDAE on Yelp-Syn, Reddit-Syn, DGraphFin, and CONAD on Reddit-Syn were unsupported under the exact fail-closed operational budget and omitted without score fabrication.")
    lines.append("\\end{tablenotes}")
    lines.append("\\end{table*}")

    content = "\n".join(lines) + "\n"

    OUT_GENERATED.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT_GENERATED, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"Generated {OUT_GENERATED} ({len(content)} bytes)")

    with open(OUT_APPENDIX, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"Updated {OUT_APPENDIX} ({len(content)} bytes)")


if __name__ == "__main__":
    generate_latex()
